### ISSUE TITLE
compile geant4 error 

### ISSUE THREAD

**Issue by ArvinShaffer** [fengsim/FENGSim-Dev#8]
Could NOT find EXPAT (missing: EXPAT_LIBRARY EXPAT_INCLUDE_DIR)

**Comment by ArvinShaffer** [comment]
`sudo apt install libexpat-devel`

**Comment by fengsim** [comment]
just libexpat1-dev enough

**Comment by fengsim** [comment]
then continue to go to `example/basic/B1` to compile the example

**Comment by ArvinShaffer** [comment]
CMake Error at cmake/Modules/Geant4InterfaceOptions.cmake:210 (message):
  could not find X11 Xmu library and/or headers
Call Stack (most recent call first):
  cmake/Modules/G4CMakeMain.cmake:64 (include)
  CMakeLists.txt:50 (include)

**Comment by ArvinShaffer** [comment]
sudo apt install libxmu-dev

**Comment by ArvinShaffer** [comment]
> then continue to go to `example/basic/B1` to compile the example

 ./exampleB1
./exampleB1: error while loading shared libraries: libG4graphics_reps.so: cannot open shared object file: No such file or directory

**Comment by ArvinShaffer** [comment]
./exampleB1
Available UI session types: [ Qt, Xm, GAG, tcsh, csh ]
./exampleB1: symbol lookup error: /usr/local/lib/libG4OpenGL.so: undefined symbol: _ZdlPvm, version Qt_5

**Comment by ArvinShaffer** [comment]
> ./exampleB1
> Available UI session types: [ Qt, Xm, GAG, tcsh, csh ]
> ./exampleB1: symbol lookup error: /usr/local/lib/libG4OpenGL.so: undefined symbol: _ZdlPvm, version Qt_5

source /usr/local/bin/geant4.sh
export LD_LIBRARY_PATH=/home/icuipi/Qt5.12.10/5.12.10/gcc_64/lib
